[window_mode]
width = 800.0
height = 600.0
maximized = false
fullscreen_type = "Windowed"
borderless = false
min_width = 10.0
min_height = 10.0
max_width = 1000.0
max_height = 1000.0
resizable = false

[window_setup]
title = "brickbeaker"
samples = "Zero"
vsync = true
icon = ""
srgb = true

[backend]
type = "OpenGL"
major = 3
minor = 2

[modules]
gamepad = false
audio = true
